name: Build and Deploy

on: [workflow_dispatch]

env:
  resourceGroupName: AzureBicepDemoRG
  bicepFilePath: main.bicep
  jsonFilePath: main.json

jobs:
  buildtest:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Bicep file
        uses: azure/cli@1.0.4
        with:
          inlineScript: |
            az bicep build --file ${{ env.bicepFilePath }} \
            --outfile ${{ env.jsonFilePath }}

      - name: Upload ARM template as artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          path: ${{ env.jsonFilePath }}
          if-no-files-found: error

      - name: Test Bicep template with What-if
        uses: azure/cli@1.0.4
        with:
          inlineScript: |
            az deployment group create \
            --resource-group ${{ env.resourceGroupName }} \
            --template-file ${{ env.bicepFilePath }} \
            --what-if --what-if-result-format ResourceIdOnly

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [buildtest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep to Azure
        uses: azure/cli@1.0.4
        with:
          inlineScript: |
            az deployment group create \
            --resource-group ${{ env.resourceGroupName }} \
            --template-file ${{ env.bicepFilePath }}