name: Build and Deploy

on:
  workflow_dispatch:

env:
  resourceGroupName: AzureBicepDemoRG
  bicepFilePath: biceptemplates/storageaccount.bicep

jobs:

  buildtest:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Bicep file
        uses: azure/cli@1.0.4
        with:
          inlineScript: |
            az bicep build --file ${{ env.bicepFilePath }} --outfile biceptemplates/storageaccount.json

      - name: Upload ARM template as artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          path: biceptemplates/storageaccount.json
          if-no-files-found: error

      - name: Test with Whatif
        uses: azure/cli@1.0.4
        with:
          inlineScript: |
            az deployment group create --resource-group ${{ env.resourceGroupName }} --template-file biceptemplates/storageaccount.json --what-if --what-if-result-format ResourceIdOnly
